# 1. Introduction 

### Advantages of numpy array over lists
- Consumes less memory.
- Fast compared to the python List.
- Flexibility in operations.

In [ ]:
# Source: https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/

##### Demo 1: Memory Comparision




In [ ]:
import numpy as np
import sys

lst = [1,2,3,4,5,6]
print(lst, type(lst), len(lst))
print(sys.getsizeof(lst))
print(sys.getsizeof(lst)*len(lst))

arr = np.array(lst)
print(arr, type(arr), arr.size )
print(arr.itemsize)
print((arr.itemsize)*arr.size)


[1, 2, 3, 4, 5, 6] <class 'list'> 6
120
720
[1 2 3 4 5 6] <class 'numpy.ndarray'> 6
8
48


##### Demo 2: Speed Comparision


In [ ]:
import time

size = 1000000
a = range(size)
b = range(size)

start = time.perf_counter()
#list(zip(a,b))
[(i*j) for i,j in zip(a,b)]
end = time.perf_counter()

elapsed = end - start
print(elapsed)

x = np.arange(size)
y = np.arange(size)
start = time.perf_counter()
z = x * y
end = time.perf_counter()

elapsed = end - start
print(elapsed)

0.14034410900012517
0.0021736119997513015


##### Demo 3: Flexibility


In [ ]:
arr = np.array([1,2,3,4])
print(arr+2)

[3 4 5 6]


# 2. Generating numpy array
1. np.array(list/tuple)
2. np.arange(start, stop, step)
3. np.linspace(start, stop, #spacedValues from start to stop)
4. np.zeros()
5. np.ones()
6. np.eye()
7. np.random.rand(#rows, #columns)
8. np.random.randn(#rows, #columns)
9. np.random.randint(start, stop, #randomValues from start to stop)

### Method I:  np.array(  list/tuple  )

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a, type(a), a.ndim)

b = np.array((1,2))
print(b)

[[1 2]
 [3 4]] <class 'numpy.ndarray'> 2
[1 2]


### Method II: np.arange ( start, stop, step )

In [ ]:
arr_c = np.arange(20)
arr_s = np.arange(20,-1,-2)
print('arange example:')
print(arr_c)
print(arr_s)

arange example:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 18 16 14 12 10  8  6  4  2  0]


### Method III: np.linspace(start, stop, #values from start to stop) 

In [ ]:
linspace_array = np.linspace(0,10,30)

print('linspace example:')
print(linspace_array)

linspace example:
[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]


### Method IV: np.zeros (  )

In [ ]:
# .zeros() built-in method is used
# generates array of zeroes
# tuple parameter = multi-dimension


z_1d = np.zeros(3) #if the argument is a single number => 1 dimensional
print('1 dimensional:')
print(z_1d)

z_2d = np.zeros((3,5)) #if argument is tuple => 2 dimensional
print('2 dimensional:')
print(z_2d)

z_3d = np.zeros((3,5,2)) #if argument is tuple with 3 elements => 3 dimensional
print('3 dimensional:')
print(z_3d)


1 dimensional:
[0. 0. 0.]
2 dimensional:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3 dimensional:
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


### Method V: np.ones (  )

In [2]:
import numpy as np

In [7]:
# .ones() built-in method is used
# generates array of ones
# 1 parameter with tuple = multi-dimension

ones_1d = np.ones(3)
print('1d example:')
print(ones_1d)

ones_2d = np.ones((3,5))
print('2d example')
print(ones_2d)

ones_3d = np.ones((3,5,2))
print('3d example')
print(ones_3d)

1d example:
[1. 1. 1.]
2d example
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3d example
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### Method VI: np.eye (  )

In [ ]:
# .eye() built-in method is used
# generates identity matrix

id_arr = np.eye(3) # only 1 parameter => 3 x 3 identitiy matrix
print('Square Matrix:')
print(id_arr)

id_arr = np.eye(3,5) # 2 parameter => 3rows x 5columns identitiy TYPE matrix
print('Non-Square Matrix:')
print(id_arr)

Square Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Non-Square Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Method VII: np.random.rand ( #rows, #columns )


In [ ]:
# .random.rand(#rows, #columns) method

random_array = np.random.rand(5,2) #2 parameters => 5rows x 2columns 
print('5 x 2 random array:')
print(random_array)

random_array2 = np.random.rand(3) #1 parameter => 1row x 3columns
print('1 x 3 random array:')
print(random_array2)

5 x 2 random array:
[[0.15992744 0.51792527]
 [0.80849759 0.48930272]
 [0.59310142 0.26442563]
 [0.070083   0.00157866]
 [0.09080352 0.78161178]]
1 x 3 random array:
[0.28355494 0.31760109 0.75165607]


### Method VIII: np.random.randn( #rows, #columns )

In [ ]:
# .random.randn(#rows, #columns) method
# generates normalized values (mean = 0, std_dev = 1)
# stand normal distribution, bell shaped values

randN = np.random.randn(5,2)
print('5 x 2 random array:')
print(randN)

randN2 = np.random.randn(3)
print('1 x 3 random array:')
print((randN2,2))

5 x 2 random array:
[[ 0.43737753 -0.01428691]
 [-0.29343017 -0.91590753]
 [-1.94454073 -0.90251709]
 [ 0.62941412 -0.61093424]
 [-0.43597134 -1.55244628]]
1 x 3 random array:
(array([1.68713952, 0.05169198, 0.86571295]), 2)


### Method IX: np.random.randint ( start(in), stop(ex), #values)

In [ ]:
# .random.randint(start(in), stop(ex), #values) method
# generates random integer array
# first 2 parameters are range: including to excluding, 3rd is # of values
# always a 1 dimensional array

# random_int_array2 = np.random.randint(1,7) #2 parameters only
# print(random_int_array2)

random_int_array = np.random.randint(1,700, 5) #2 parameters only
print(random_int_array)

[149 107 234  76  27]


In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
np.linspace(25, 100, 10)

array([ 25.        ,  33.33333333,  41.66666667,  50.        ,
        58.33333333,  66.66666667,  75.        ,  83.33333333,
        91.66666667, 100.        ])

In [ ]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.zeros((2,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.random.randn(3)

array([-0.23643433, -1.22790105,  0.95224086])

In [ ]:
np.random.randint(12,35,10)

array([18, 14, 26, 30, 14, 22, 22, 22, 18, 21])

# 3. *numpy* Methods
- shape and reshape
- transpose
- basic math operations
- methods with array as parameter

### a. shape and reshape


In [ ]:
#.shape() -  provides dimension of the array
#.reshape() - changes dimension of the array

#shape
# a = np.array([[1,2,3],[4,5,6]])
# print(a)
# print(a.shape)

#1d to reshape
x = np.random.randint(1,100,20)
print(x)

#20
#10 x 2
y = x.reshape(2,10)
print(y)
# 2 x 10
# 5 x 4
# 4 x 5
# 1 x 20
# 20 x 1

#2d to reshape
p = np.array([[1,2,3],[4,5,6]])
print(p, p.shape)

# 6
# 2 x 3
q = p.reshape(1,6)
print(q)
# 3 x 2
# 6 x 1
# 1 x 6

#3d to reshape
n = np.ones((5,4, 2))
print(n, n.shape, n.ndim)

# 8
# 4 x 2
# 8 x 1
m = n.reshape((8,1))
print(m)
# 1 x 8
# 2 x 4



[96 50 54 43 69 11 25 24 35 94 46 87 75 74 72 60 72 30 40 60]
[[96 50 54 43 69 11 25 24 35 94]
 [46 87 75 74 72 60 72 30 40 60]]
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2 3 4 5 6]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]] (5, 4, 2) 3


ValueError: ignored

### b. transpose


In [ ]:
#.T transposes an array
x = np.array([[1,2,3],[4,5,6]])
print(x, x.shape)

y = x.T
print(y, y.shape)




[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


### c. basic math operations


In [ ]:
x = np.random.randint(1, 100, 20)
x_new = x.reshape(5,4)

print('x_new:\n', x_new)
print('multiply by 2\n', x_new*2)
print('add 2\n', x_new+2)
print('divide by 2\n', x_new/2)
print('power of 5\n', x_new**5)
print('multiply by iteself\n', x_new * x_new)
print('multiply by itself thrice\n', x_new * x_new * x_new)

x_new:
 [[52 60 15 63]
 [48 70 95 11]
 [67  1 33 41]
 [35 74 66 67]
 [55 92 95  8]]
multiply by 2
 [[104 120  30 126]
 [ 96 140 190  22]
 [134   2  66  82]
 [ 70 148 132 134]
 [110 184 190  16]]
add 2
 [[54 62 17 65]
 [50 72 97 13]
 [69  3 35 43]
 [37 76 68 69]
 [57 94 97 10]]
divide by 2
 [[26.  30.   7.5 31.5]
 [24.  35.  47.5  5.5]
 [33.5  0.5 16.5 20.5]
 [17.5 37.  33.  33.5]
 [27.5 46.  47.5  4. ]]
power of 5
 [[ 380204032  777600000     759375  992436543]
 [ 254803968 1680700000 7737809375     161051]
 [1350125107          1   39135393  115856201]
 [  52521875 2219006624 1252332576 1350125107]
 [ 503284375 6590815232 7737809375      32768]]
multiply by iteself
 [[2704 3600  225 3969]
 [2304 4900 9025  121]
 [4489    1 1089 1681]
 [1225 5476 4356 4489]
 [3025 8464 9025   64]]
multiply by itself thrice
 [[140608 216000   3375 250047]
 [110592 343000 857375   1331]
 [300763      1  35937  68921]
 [ 42875 405224 287496 300763]
 [166375 778688 857375    512]]


### d. Methods with array as parameter
- sqrt( ), max( ), min( ), argmax( ), argmin( ), log( ), sin( ), round( )

In [ ]:
#sqrt(array)
array_ = np.random.randint(1,100,20)
array_ = array_.reshape(5,4)
print('array_:')
print(array_)

print('sqrt:')
print(np.sqrt(array_))
#max(array)
print('max:')

print(np.max(array_))

#min(array)
print('min:')

print(np.min(array_))

#argmax(array)
print('argmax:')

print(np.argmax(array_))

#argmin(array)
print('argmin:')

print(np.argmin(array_))

#log(array)
print('log:')

print(np.log(array_))

#sin(array)
print('sin:')

print(np.sin(array_))

#round(array, decimals = 3)
print('round:')
array_n = np.random.randn(4,5)
print(array_n)
print(np.round(array_n, decimals =2))

array_:
[[85 27 38 48]
 [15 49 86 59]
 [49  9 45 56]
 [85 19 16 94]
 [83 22 10 71]]
sqrt:
[[9.21954446 5.19615242 6.164414   6.92820323]
 [3.87298335 7.         9.2736185  7.68114575]
 [7.         3.         6.70820393 7.48331477]
 [9.21954446 4.35889894 4.         9.69535971]
 [9.11043358 4.69041576 3.16227766 8.42614977]]
max:
94
min:
9
argmax:
15
argmin:
9
log:
[[4.44265126 3.29583687 3.63758616 3.87120101]
 [2.7080502  3.8918203  4.4543473  4.07753744]
 [3.8918203  2.19722458 3.80666249 4.02535169]
 [4.44265126 2.94443898 2.77258872 4.54329478]
 [4.41884061 3.09104245 2.30258509 4.26267988]]
sin:
[[-0.17607562  0.95637593  0.29636858 -0.76825466]
 [ 0.65028784 -0.95375265 -0.92345845  0.63673801]
 [-0.95375265  0.41211849  0.85090352 -0.521551  ]
 [-0.17607562  0.14987721 -0.28790332 -0.24525199]
 [ 0.96836446 -0.00885131 -0.54402111  0.95105465]]
round:
[[-1.46626967 -1.5901135  -0.8354999  -0.0215463  -0.57910677]
 [-0.1904561   1.33022863 -2.00581017 -0.30838982 -0.61689339]
 [ 

### e. .dtype property


In [ ]:
x = np.random.randint(1,30,15)
print(x, x.dtype)
y = np.eye(7)
print(y, y.dtype)

[24 10  6 11 13 23 12  4 28  9 24 11 10 23 18] int64
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]] float64


### f. .copy() method


In [ ]:
x = np.ones((4,2))
print(x)
x1 = x.copy()
x1 = x1 + 2
print(x1)
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

# 4.  *numpy* Indexing
- One Dimensional Array
 1. Single Value Indexing
 2. Multiple Value Indexing
 3. Slicing
 4. Updation using Slicing
- Two Dimensional Array
 1. All elements of column(s)
 2. All elements of row(s)
 3. Combination of row(s) and column(s)

## a. One Dimensional Array

### Case i: Single Value Indexing

In [ ]:
lst = list(range(0,11))
print(lst, lst[7], lst[10])

npa =np.arange(0,11)
print(npa, npa[7], npa[10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 7 10
[ 0  1  2  3  4  5  6  7  8  9 10] 7 10


### Case ii: Multiple Value Indexing

In [ ]:
lst = list(range(0,11))

#print(lst[0,2,6,8]) #not possible in Python
#print(lst[[0,2,6,8]]) #not possible in Python

npa = np.arange(0,11)

print(npa)
print(npa[[0,2,6,8]]) #passing a list of indices
#print(npa[0,2,6,8]) #results in error

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 2 6 8]


### Case iii: Slicing

In [ ]:
lst = list(range(10))
npa = np.arange(10)

print(lst)
print(lst[0:5])
print(npa)
print(npa[0:5])


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


### Case iv: Updation using Slicing



In [ ]:
lst = list(range(10))
npa = np.arange(10)

print(lst)
lst[11:13] = [77,777]
print(lst)
print(npa)
#npa[11:13] = [77,777] #not possible

npa[0:7] = 888
print(npa)

#lst[0:7] = 888 #not possible


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 77, 777]
[0 1 2 3 4 5 6 7 8 9]
[888 888 888 888 888 888 888   7   8   9]


In [ ]:
#SUMMARY: updating values posibility (list vs. numpy array)
#Single value updating:                             list and numpy array
#Slicing update of existing index:                  list and numpy array
#Slicing update of NEW index:                       list 
#Slicing update of multi indices with single value: numpy array

#CONCLUSION: Creating new indices on the go and updating values for a numpy array is not possible

## b. Two Dimensional Array

### Case i: All elements of column(s)







In [ ]:
array_2d = np.arange(1,21).reshape(4,5)
#case (i): 

print(array_2d, array_2d.shape)


print('all elements of 0th index column:')
print(array_2d[:, 0]) #all elements of column 0

print('all elements of 0th index row and 1st index column:')
print(array_2d[:, (0,1)]) #all elements of column 0 and 1


print(array_2d[:, (0,4)]) #all elements of column 0 and 4
print(array_2d[:, 0:4]) #all elements from column 0 to column 3

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5)
all elements of 0th index column:
[ 1  6 11 16]
all elements of 0th index row and 1st index column:
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
[[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


### Case ii: All elements of row(s)


In [ ]:
array_2d = np.arange(1,21).reshape(4,5)
#case (ii): 

print(array_2d, array_2d.shape)
print()
print(array_2d[0,:]) #entire first row
print()
print(array_2d[(0,1),:]) #0th index row and 1st index row
print()
print(array_2d[(0,3),:])#0th index row and 3rd index row
print()
print(array_2d[0:3,:]) #from 0th index row to 2nd index row

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5)

[1 2 3 4 5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Case iii: Combination of row(s) & column(s)


In [ ]:
array_2d = np.arange(1,21).reshape(4,5)
#case (iii): 

print(array_2d, array_2d.shape)
print(array_2d[0,0])
#print(array_2d[0][0])
print(array_2d[(0,2),(2,4)]) 
print()
print(array_2d[0:2, 0:2])
print()
print(array_2d[0:2, 2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5)
1
[ 3 15]

[[1 2]
 [6 7]]

[[3 4]
 [8 9]]


In [ ]:
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
array_2d[0,0]

1

In [ ]:
array_2d[0][0]

1

In [ ]:
array_2d[0,0] = array_2d[0][0]

In [ ]:
array_2d[3][4]

20

# 5. Selection and Saving

### a. numpy Selection

In [ ]:
lst = list(range(0,11))
print(lst)
#print(lst<5) #not possible
#print(lst[lst<5]) #notpossible

npa =np.arange(0,11)
print(npa)
print(npa<5)
print(npa[npa<5])

arr = np.random.randint(1,100,49).reshape(7,7)
print(arr)
print(arr<75)
print(arr[arr<75])
print(arr.ndim)
print(arr[arr<75].ndim)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True  True False False False False False False]
[0 1 2 3 4]
[[70 61 19 65 35 41 84]
 [56 12 54 47 60 20  6]
 [19 97 39 74  7  7 95]
 [78 88 76  1  3 72 77]
 [98 59 12 37 41 30 62]
 [ 8 77 37 33 41  3 29]
 [84 67 13 38 82 71 21]]
[[ True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True]
 [ True False  True  True  True  True False]
 [False False False  True  True  True False]
 [False  True  True  True  True  True  True]
 [ True False  True  True  True  True  True]
 [False  True  True  True False  True  True]]
[70 61 19 65 35 41 56 12 54 47 60 20  6 19 39 74  7  7  1  3 72 59 12 37
 41 30 62  8 37 33 41  3 29 67 13 38 71 21]
2
1


### b. Saving

#### Case(i): Saving to .npy format using np.save(  )





In [ ]:
x = np.random.randn(2,3,4)
print(x, x.ndim)
np.save('arr_name', x)



[[[-1.48141239  0.93195964 -0.54264023 -0.23340503]
  [ 1.10856104 -0.09544499 -0.79744163 -0.54934975]
  [ 0.00255927 -0.96267947  1.00739643  1.14420397]]

 [[ 0.69743371 -0.42772385 -0.73769151  0.74861025]
  [-1.99563767  0.61375312  0.48653919  0.21642569]
  [ 0.53263324 -1.03803025  0.77001034 -0.43555242]]] 3


In [ ]:
np.load('arr_name.npy')

array([[[-1.48141239,  0.93195964, -0.54264023, -0.23340503],
        [ 1.10856104, -0.09544499, -0.79744163, -0.54934975],
        [ 0.00255927, -0.96267947,  1.00739643,  1.14420397]],

       [[ 0.69743371, -0.42772385, -0.73769151,  0.74861025],
        [-1.99563767,  0.61375312,  0.48653919,  0.21642569],
        [ 0.53263324, -1.03803025,  0.77001034, -0.43555242]]])

#### Case(ii): Saving to .csv format using np.savetxt(  )

---




In [ ]:
x = np.random.randint(1,100,49).reshape(7,7)
print(x)
np.savetxt('myArray', x)



[[56 88 74  1  3 20 47]
 [80  8 87 94 32 38 48]
 [76  2 87 85 88 71 20]
 [29 20 99 60 72  4 59]
 [59  6  3 30  2  4 68]
 [10 77 71 41 96  2 60]
 [77 51 17 38 19  4 70]]


# 6. Summary

## Array Creation


1. np.array(list/tuple)
2. np.arange(start, stop, step)
3. np.linspace(start, stop, #spacedValues from start to stop)
4. np.zeros()
5. np.ones()
6. np.eye()
7. np.random.rand(#rows, #columns)
8. np.random.randn(#rows, #columns)
9. np.random.randint(start, stop, #randomValues from start to stop)


In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.ones((7,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.array([1,2,3]) #column array
np.array([[1,2,3]])

array([[1, 2, 3]])

In [ ]:
np.random.randint(1,25,10)

array([ 2,  7, 23, 18,  8, 16, 23,  6, 24, 10])

10. np.full()



In [ ]:
np.full((5,4),7, dtype = 'float64')

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

## Properties

- shape and reshape
- transpose
- basic math operations
- methods with array as parameter
- dtype


---



In [ ]:
np.random.randint(1,25,10).reshape(2,5)

array([[14,  4,  6, 12,  2],
       [11, 15,  1,  5,  6]])

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)
print(x.shape[0])
print(x.shape[1])

(2, 3)
2
3


- x.size/np.size()

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
#x.size
print(x)
print(np.size(x, axis = 0)) #rows
print(np.size(x, axis = 1)) #columns



[[1 2 3]
 [4 5 6]]
2
3


## Methods

- sqrt( ), max( ), min( ), argmax( ), argmin( ), log( ), sin( ), round( )
- copy()

---




- sum()
- mean()
- column_stack()
- linalg.pinv()

In [ ]:
x = np.arange(1,11)
print(x)
print(np.sum(x))
print(np.mean(x))

y = np.random.randint(1,10, 6).reshape(3,2)
print(y)
print()
print(np.sum(y, axis = 1))
print()
print(np.mean(y, axis = 1))



[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
[[3 8]
 [3 6]
 [1 3]]

[11  9  4]

[5.5 4.5 2. ]


In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

# print(x)
# print(y)

# z= np.column_stack((x,y))
# print(z)

p = np.column_stack((np.ones(x.shape[0]),x))
print(p)

[[1. 1.]
 [1. 2.]
 [1. 3.]]
