# Solutions - numpy Creation

---



### Q1. Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 4 numbers, for example: 0, 4, 8 ....

In [ ]:
#@title
np.arange(0,101,4)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

### Q2. Output a sequence of equally gapped 7 numbers in the range 0 to 100 (both inclusive)

In [ ]:
#@title
np.linspace(0,100,7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

### Q3. Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive) using size = (5,5) parameter instead on reshape property

In [ ]:
#@title
np.random.seed(123) #setting the seed
# Your answer below:
np.random.randint(0,10,size=(5,5))

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3],
       [4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7]])

### Q4. Output a 3-by-3 array of random numbers following normal distribution


In [ ]:
#@title
np.random.seed(123) #setting the seed
# Your answer below:
np.random.randn(3,3)

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654],
       [-2.42667924, -0.42891263,  1.26593626]])

### Q5. Generate a numpy array of 4 rows and 5 columns with all values 1 and also print the dimesion of the array using ndim property

In [ ]:
#@title
x = np.ones((4,5))
print(x,x.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 2


### Q6. Output a 3 dimesnional zeros numpy array of shape (3,4,5)

In [ ]:
#@title
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### Q7. Output a 2 dimensional ones numpy array of shape (7,2)

In [ ]:
#@title
np.ones((7,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Q8. Create a numpy array to output: array([ 20,  13,   6,  -1,  -8, -15])


In [ ]:
#@title
np.arange(20,-20,-7)

array([ 20,  13,   6,  -1,  -8, -15])

### Q9. What is dimension of np.array( [ 1 , 2 ] ) Vs.np.array( [ [ 1 , 2 ] ] )

In [ ]:
#@title
print(np.array([1,2]).ndim)
print(np.array([[1,2]]).ndim)

1
2


### Q10. Using np.full( ), create a 4 x 5 numpy array with each value of the numpy array being 47

In [ ]:
#@title
np.full((4,5),47)

array([[47, 47, 47, 47, 47],
       [47, 47, 47, 47, 47],
       [47, 47, 47, 47, 47],
       [47, 47, 47, 47, 47]])