# Solutions - numpy Methods

---



### Q1. Create any 2 similar dimensional numpy arrays, preferrable 4 x 5 and perform element-wise sum of the 2 numpy arrays?



In [3]:
import numpy as np
np.random.seed(123)
x = np.random.randint(1,100,20).reshape(4,5)
y = np.random.randint(1,100,20).reshape(4,5)
print(x)
print(y)
print(x + y)



[[67 93 99 18 84]
 [58 87 98 97 48]
 [74 33 47 97 26]
 [84 79 37 97 81]]
[[69 50 56 68  3]
 [85 40 67 85 48]
 [62 49  8 93 53]
 [98 86 95 28 35]]
[[136 143 155  86  87]
 [143 127 165 182  96]
 [136  82  55 190  79]
 [182 165 132 125 116]]


### Q2. Create this numpy array -> [1 2 3 4 5 6 ], reshape it to 2 x 3 and scalar multiply each element of this reshaped array with 7

In [5]:
x = np.array([1,2,3,4,5,6]).reshape(2,3)
print(x)
print(x * 7)

[[1 2 3]
 [4 5 6]]
[[ 7 14 21]
 [28 35 42]]


### Q3. Convert a 1-D array to a 3-D array



In [20]:
x = np.arange(1,28)
print(x)
print(x.reshape(3,3,3))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Q4. Refer the documentation and create an example using np.hstack( ) method

In [25]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
print(x)
print()
print(y)
print()
z = np.hstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


### Q5. Refer the documentation and create an example using np.vstack( ) method

In [26]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
print(x)
print()
print(y)
print()
z = np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


### Q6. Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)
    a = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

    b = np.array([[2,3,4],
                  [5,6,7],
                  [8,9,10]])


In [29]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

b = np.array([[2,3,4], [5,6,7], [8,9,10]])


print(a @ b)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


### Q7. Write a NumPy program to reverse an array (first element becomes last). 
- Original array:
[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
- Reverse array:
[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4, 3,  2,  1]

In [31]:
x = np.arange(1,21)
print(x)
y = x[::-1]
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


### Q8. Create a NumPy array and convert it to a float type.


In [33]:
np.full((2,3),6, dtype = 'float64')

array([[6., 6., 6.],
       [6., 6., 6.]])

### Q9. Using np.full( ), create a 4 x 5 numpy array with each value of the numpy array being 47 and convert it into float type

In [34]:
np.full((4,5),47, dtype = 'float64')

array([[47., 47., 47., 47., 47.],
       [47., 47., 47., 47., 47.],
       [47., 47., 47., 47., 47.],
       [47., 47., 47., 47., 47.]])

### Q10. Create any 3d numpy array and find a) minimum value b) maximum value c) index of minimum value d) index of maximum value e) create copy of the array using copy method

In [46]:
x = np.random.randint(1,100,18).reshape(3,2,3)
print(x, x.ndim)
print('-----------------')
x1 = x.copy()
print(x1, x1.ndim)

[[[10 88 90]
  [72  5 13]]

 [[86 34 25]
  [23 85  3]]

 [[ 8 46 62]
  [39 51 22]]] 3
-----------------
[[[10 88 90]
  [72  5 13]]

 [[86 34 25]
  [23 85  3]]

 [[ 8 46 62]
  [39 51 22]]] 3
