# 5.0 Solutions: Selections and Saving

### Q1. Follow the instructions below:
1. Create a numpy array of shape 7 x 5 using 
-  a) np.random.randint(1,100,35) 
-   b) reshape property  
2. Replace all elements of that numPy array that are greater than 75 with 0 

In [17]:
import numpy as np
np.random.seed(123)
arr_x = np.random.randint(1,100,35).reshape(7,5)
print(arr_x)
print()
arr_x[arr_x>75] = 0
print(arr_x)


[[67 93 99 18 84]
 [58 87 98 97 48]
 [74 33 47 97 26]
 [84 79 37 97 81]
 [69 50 56 68  3]
 [85 40 67 85 48]
 [62 49  8 93 53]]

[[67  0  0 18  0]
 [58  0  0  0 48]
 [74 33 47  0 26]
 [ 0  0 37  0  0]
 [69 50 56 68  3]
 [ 0 40 67  0 48]
 [62 49  8  0 53]]


### Q2. Write a NumPy program to select the elements from the second array corresponding to elements in the first array that are greater than 10 and less than 20
Input:
> a = np.array([7, 11, 15, 19, 27])

> b = np.array(['a','e','i','o','u'])


Expected Output:
> [ 'e' 'i' 'o' ]

In [ ]:
a = np.array([7, 11, 15, 19, 27])
b = np.array(['a','e','i','o','u'])
z = b[(a>10) & (a<20)]
print(z)


['e' 'i' 'o']


### Q3. Create a numpy array [-6 -5 -4 -3 -2 -1  0  1  2  3  4  5] and find the index of the array whose value is greater than 2
- Hint: expected output is 9

In [ ]:
x = np.array([-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5] )
print(x)
print()
print(np.argmax([x>2]))

[-6 -5 -4 -3 -2 -1  0  1  2  3  4  5]

9


### Q4.  Write a program to create a numpy array  x = [-6 -5 -4 -3 -2 -1  0  1  2  3  4  5] and from it, generate another array, satisfying the condition x > 3
- Hint: expected output is [4 5]

In [ ]:
x = np.array([-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5] )
print(x)
print()
print(x[x>3])

[-6 -5 -4 -3 -2 -1  0  1  2  3  4  5]

[4 5]


### Q5. Write a numPy program to fetch all items from a  array of 4,5 shape extracted from np.arange(20) with following conditions:
- Greater than 6 and 
- Multiple of 3



In [ ]:
x = np.arange(20).reshape(4,5)
print(x)
print()
print(x[(x>6)&(x%3==0)])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[ 9 12 15 18]


### Q6. Save the numpy array from Q1 in .npy format

In [18]:
np.save('array1', arr_x)

### Q7. Load the numpy array saved in Q6 

In [19]:
np.load('array1.npy')

array([[67,  0,  0, 18,  0],
       [58,  0,  0,  0, 48],
       [74, 33, 47,  0, 26],
       [ 0,  0, 37,  0,  0],
       [69, 50, 56, 68,  3],
       [ 0, 40, 67,  0, 48],
       [62, 49,  8,  0, 53]])

### Q8. Save the numpy array from Q1 in .txt format

In [21]:
np.savetxt('array2', arr_x)

### Q9. Save the numpy array from Q1 using np.savez() method (refer documentation)

In [24]:
np.savez('array3', arr_x)

### Q10. Load the numpy array saved in Q8

In [23]:
np.loadtxt('array2')

array([[67.,  0.,  0., 18.,  0.],
       [58.,  0.,  0.,  0., 48.],
       [74., 33., 47.,  0., 26.],
       [ 0.,  0., 37.,  0.,  0.],
       [69., 50., 56., 68.,  3.],
       [ 0., 40., 67.,  0., 48.],
       [62., 49.,  8.,  0., 53.]])